apiVersion: v1
kind: Service
metadata:
  name: eks-ademo
  namespace: eks-ademo
  labels:
    app: eks-ademo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: eks-ademo
